install:
    - "sudo apt-get update -qq"
    - "sudo apt-get install linkchecker -qq"
    - "rvm use 1.9.3@test --create"
    - "gem install jekyll"
    - "gem install redcarpet"
before_script:
    - "bash -c 'jekyll --server 1234 &'"
    - "sleep 5"
script:
    - "linkchecker --no-warnings http://localhost:1234/"
