notifications:
  email:
    recipients:
      - chris+travis@chrisdown.name
    on_success: never
    on_failure: always

sudo: required
dist: trusty

rvm:
  - ruby-2.1.2

before_install:
    - sudo add-apt-repository ppa:techzilla/misc -y
    - sudo apt-get update -q
install:
    - sudo pip install requests
    - sudo pip install git+https://github.com/linkcheck/linkchecker.git
    # The signatures on the Techzilla PPA are busted, sadly. :-(
    - sudo apt-get install tidy --force-yes
    - bundle install
before_script:
    - 'tidy -v'
    - "jekyll serve --port 24895 &"
    - sleep 10
script:
    # Testing external links can be kinda flaky, so as long as one of the three
    # attempts passes, we consider everything to be OK. If the site is flaky,
    # it's ok, as long as the link isn't dead.
    - |
      for (( i=0; i<3; i++ )); do
        linkchecker -a --no-warnings http://localhost:24895 \
          --check-extern && break
      done
    # `tidy` doesn't allow you to ignore warnings in exit codes, so we need to
    # explicitly check for errors with `grep`.
    - "! find deploy/ -name '*.html' -exec tidy -e {} + 2>&1 | LC_ALL=C grep '[0-9] error' | grep -v '0 error'"
    # If you don't specify the link for an anchor, Jekyll is a bit funny and
    # lets it go through without fatalling (and sets the link to nothing). We
    # manually check for these to avoid that.
    - "! grep -R 'href=\"\"' _deploy"
    # Newer versions of the markdown interpreter just put the raw anchor text
    # if you failed to give it a link reference, so we should look for those
    # too.
    - "! grep -IFR '][]' _deploy/"
