name: &name Chris Down
url: "http://chrisdown.name"

personal:
    name: *name
    job: Sysadmin
    employers:
        - name: "Initiatives of Change"
          url: "http://iofc.org"
        - name: "BetOnMarkets"
          url: "https://betonmarkets.com"
    email: chris@chrisdown.name

header:
    links: []

footer:
    links:
        - name: GitHub
          url: "https://github.com/cdown/"
        - name: Stack Exchange
          url: "http://stackexchange.com/users/912213/chris-down?tab=accounts"

projects:
    - name: yturl
      url: "http://git.chrisdown.name/cgit/yturl/"
      description: Gets direct URLs to YouTube media
    - name: clarity
      url: "http://git.illco.de/cgit/clarity/"
      description: A digital signage system for minimalists
