source: .
destination: ./_site

name: &name Chris Down
url: "http://chrisdown.name"

links:
    iofc: &iofc-url "http://iofc.org"
    bom: &bom-url "https://betonmarkets.com"
    github: &github-url "https://github.com/cdown"
    stackexchange: &stackexchange-url "http://unix.stackexchange.com/users/10762/chris-down"
    aur: &aur-url "https://aur.archlinux.org/packages/?SeB=m&amp;K=cdown"

personal:
    name: *name
    job: Sysadmin
    employers:
        - name: "IofC"
          url: *iofc-url
        - name: "BetOnMarkets"
          url: *bom-url
    email:
        scrim: chrisdown
        account: chris
    phone:
        malaysia: "+60(0)1118625221"
        uk: "+44(0)7926811688"

header:
    links:
        - name: github
          url: *github-url
        - name: projects
          url: /projects

projects:
    - name: auditall
      path: "/cdown/auditall"
      description: Generate audit rules for a host and its containers
    - name: chrisdown.name
      path: "/cdown/cdown.github.com"
      description: Personal website
    - name: clarity
      path: "/illcode/clarity"
      description: Digital signage for minimalists
    - name: mac-cel
      path: "/cdown/mac-cel"
      description: Disable mouse/trackpad acceleration on Mac OSX
    - name: pyaur
      path: "/cdown/pyaur"
      description: Python 3 (and 2) Arch User Repository interface
    # - name: rabbi
    #   path: "/cdown/rabbi"
    #   description: Automates building rsnapshot configs and cron jobs
    - name: wifilogin
      path: "/cdown/wifilogin"
      description: Bypass captive portal login
    - name: yturl
      path: "/cdown/yturl"
      description: Gets direct URLs to YouTube media
