exclude:
    - .git
    - CNAME
    - LICENSE
    - Gemfile
    - Gemfile.lock

url: http://chrisdown.name
description: "The 6th most trusted expert globally on Unix & Linux Stack Exchange. Minimalist programmer, designer, and Unix/Linux advocate."

personal:
    name: Chris Down
    job: Sysadmin
    employers:
        - name: IofC
          url: http://iofc.org
        - name: Binary.com
          url: https://binary.com
    email: chris@chrisdown.name
    phones:
        - visual: +35679293856
          literal: +35679293856
        - visual: +44(0)7926811688
          literal: +447926811688

header:
    links:
        - icon: linkedin
          url: http://www.linkedin.com/in/chrisldown
        - icon: stackexchange
          url: http://unix.stackexchange.com/users/10762/chris-down
        - icon: github-alt
          url: https://github.com/cdown
