source: source
destination: deploy
layouts: ../layouts

pygments: true

exclude:
    - .git
    - CNAME
    - LICENSE
    - Gemfile
    - Gemfile.lock

name: "Chris Down"
description:
    "I'm a minimalist programmer and designer with strong experience in
    Unix/Linux, currently living in Malaysia."
url: "http://chrisdown.name"

links:
    caux: http://caux.ch
    binary: &binary https://binary.com
    iofc: &iofc http://iofc.org
    rmg: &rmg http://regentmarkets.com
    github: &github https://github.com/cdown
    ulse: &ulse http://unix.stackexchange.com/users/10762/chris-down
    linkedin: &linkedin http://www.linkedin.com/in/chrisldown

personal:
    name: Chris Down
    job: Sysadmin
    employer:
        name: Binary.com
        url: *binary
    email: chris@chrisdown.name
    phone: +35679293856

header:
    links:
        - icon: linkedin
          url: *linkedin
          title: My LinkedIn profile
        - icon: stackexchange
          url: *ulse
          title: My Unix & Linux Stack Exchange profile
        - icon: github-alt
          url: *github
          title: My GitHub profile
