source: source
destination: deploy
layouts: ../layouts

exclude:
    - .git
    - CNAME
    - LICENSE
    - Gemfile
    - Gemfile.lock

description:
    "The 6th most trusted expert globally on Unix & Linux Stack Exchange.
    Minimalist programmer, designer, and Unix/Linux advocate."

links:
    caux: http://caux.ch
    iofc: &iofc http://iofc.org
    rmg: &rmg http://regentmarkets.com
    github: &github https://github.com/cdown
    ulse: &ulse http://unix.stackexchange.com/users/10762/chris-down
    linkedin: &linkedin http://www.linkedin.com/in/chrisldown

personal:
    name: Chris Down
    job: Sysadmin
    employers:
        - name: IofC
          url: *iofc
        - name: Regent Markets Group
          url: *rmg
    email: chris@chrisdown.name
    phone_numbers:
        - +35679293856
        - +447926811688

header:
    links:
        - icon: linkedin
          url: *linkedin
          title: My LinkedIn profile
        - icon: stackexchange
          url: *ulse
          title: My Unix & Linux Stack Exchange profile
        - icon: github-alt
          url: *github
          title: My GitHub profile
