exclude:
    - .git
    - CNAME
    - LICENSE
    - Gemfile
    - Gemfile.lock

description: >
    The 6th most trusted expert globally on Unix & Linux Stack Exchange.
    Minimalist programmer, designer, and Unix/Linux advocate.

personal:
    name: Chris Down
    job: Sysadmin
    employers:
        - name: IofC
          url: http://iofc.org
        - name: Binary.com
          url: https://binary.com
    email: chris@chrisdown.name
    phone_numbers:
        - +35679293856
        - +447926811688

header:
    links:
        - icon: linkedin
          url: http://www.linkedin.com/in/chrisldown
          title: My LinkedIn profile
        - icon: stackexchange
          url: http://unix.stackexchange.com/users/10762/chris-down
          title: My Unix & Linux Stack Exchange profile
        - icon: github-alt
          url: https://github.com/cdown
          title: My GitHub profile
