source: .
destination: ./_site

exclude:
    - .git
    - CNAME
    - LICENSE

name: &name Chris Down
url: "http://chrisdown.name"

links:
    iofc: &iofc-url "http://iofc.org"
    bom: &bom-url "https://betonmarkets.com"
    github: &github-url "https://github.com/cdown"
    stackexchange: &stackexchange-url "http://unix.stackexchange.com/users/10762/chris-down"
    aur: &aur-url "https://aur.archlinux.org/packages/?SeB=m&amp;K=cdown"
    linkedin: &linkedin-url "http://www.linkedin.com/in/chrisldown"

personal:
    name: *name
    job: Sysadmin
    employers:
        - name: "IofC"
          url: *iofc-url
        - name: "BetOnMarkets"
          url: *bom-url
    email:
        scrim: chrisdown
        account: chris
    phone:
        malaysia: "+60(0)1118625221"
        uk: "+44(0)7926811688"

header:
    links:
        - name: LinkedIn
          url: *linkedin-url
        - name: GitHub
          url: *github-url
