name: Chris Down
url: https://chrisdown.name

links:
  github: https://github.com/cdown
  ulse: https://unix.stackexchange.com/users/10762/chris-down?tab=topactivity
  linkedin: https://www.linkedin.com/in/chrisldown

personal:
  name: Chris Down
  job: System Administrator
  employer:
    name: Facebook
    url: https://facebook.com
  email:
    account: chris
    scrim: chrisdown

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - Rakefile
  - env
  - _posts_todo

destination: _deploy

highlighter: pygments

# TODO: inherit some of these from site.links

header:
  links:
    - icon: book
      url: /archive.html
      title: Blog archive
    - icon: linkedin
      url: https://www.linkedin.com/in/chrisldown
      title: My LinkedIn profile
    - icon: stackoverflow
      url: https://unix.stackexchange.com/users/10762/chris-down?tab=topactivity
      title: My Unix & Linux Stack Exchange profile
    - icon: github
      url: https://github.com/cdown
      title: My GitHub profile
    - icon: twitter
      url: https://twitter.com/unixchris
      title: My Twitter profile

plugins:
  - jekyll-redirect-from

# Disable smart quotes
kramdown:
  smart_quotes: ["apos", "apos", "quot", "quot"]
