name: Chris Down
url: https://chrisdown.name

links:
  github: &github https://github.com/cdown
  ulse: &ulse http://unix.stackexchange.com/users/10762/chris-down
  linkedin: &linkedin http://www.linkedin.com/in/chrisldown

personal:
  name: Chris Down
  job: Systems Administrator
  employer:
    name: Facebook
    url: https://facebook.com
  email:
    account: chris
    scrim: chrisdown

header:
  links:
    - icon: book
      url: /archive.html
      title: Blog archive
    - icon: linkedin
      url: *linkedin
      title: My LinkedIn profile
    - icon: stackexchange
      url: *ulse
      title: My Unix & Linux Stack Exchange profile
    - icon: github-alt
      url: *github
      title: My GitHub profile

builds:
  - name: chinese-tools
  - name: chrisdown.name
    disable:
      - coveralls
      - scrutinizer
      - requires  # TODO: Ruby requires?
  - name: defeat
  - name: download-flickr-set
  - name: fix-srt-order
  - name: gh-mirror
  - name: imurl
  - name: jingui
  - name: osmo
  - name: pinyin
  - name: pyaur
  - name: radiusweb
  - name: rtorrent-cookbook
    disable:
      - coveralls
      - scrutinizer
      - requires
  - name: scurl
  - name: tinysrt
  - name: tzupdate
  - name: yturl

source: source
plugins: plugins
destination: deploy
layouts: ../layouts
