name: &name Chris Down
url: "http://chrisdown.name"

links:
    iofc: &iofc-url "http://iofc.org"
    bom: &bom-url "https://betonmarkets.com"
    github: &github-url "https://github.com/cdown"
    stackexchange: &stackexchange-url "http://stackexchange.com/users/912213/chris-down?tab=accounts"
    internal-git: &internal-git "http://git.chrisdown.name"

personal:
    name: *name
    job: Sysadmin
    employers:
        - name: "Initiatives of Change"
          url: *iofc-url
        - name: "BetOnMarkets"
          url: *bom-url
    email: chris@chrisdown.name

header:
    links: []

footer:
    links:
        - name: GitHub
          url: *github-url
        - name: Stack Exchange
          url: *stackexchange-url

projects:
    - name: yturl
      url: "http://git.chrisdown.name/cgit/yturl/"
      description: Gets direct URLs to YouTube media
    - name: clarity
      url: "http://git.illco.de/cgit/clarity/"
      description: A digital signage system for minimalists
