name: Chris Down
url: https://chrisdown.name

links:
  github: https://github.com/cdown
  ulse: http://unix.stackexchange.com/users/10762/chris-down
  linkedin: https://www.linkedin.com/in/chrisldown

personal:
  name: Chris Down
  job: System Administrator
  employer:
    name: Facebook
    url: https://facebook.com
  email:
    account: chris
    scrim: chrisdown

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - Rakefile
  - env

destination: _deploy

highlighter: pygments
