name: Chris Down
url: https://chrisdown.name

links:
    caux: http://caux.ch
    facebook: &facebook https://facebook.com
    iofc: &iofc http://iofc.org
    rmg: &rmg http://regentmarkets.com
    github: &github https://github.com/cdown
    ulse: &ulse http://unix.stackexchange.com/users/10762/chris-down
    linkedin: &linkedin http://www.linkedin.com/in/chrisldown
    internal-git: http://git.chrisdown.name
    blog: &blog /archive.html

personal:
    name: Chris Down
    job: Systems Administrator (Security)
    employer:
        name: Facebook
        url: *facebook
    email:
        account: chris
        scrim: chrisdown

header:
    links:
        - icon: book
          url: *blog
          title: Blog archive
        - icon: linkedin
          url: *linkedin
          title: My LinkedIn profile
        - icon: stackexchange
          url: *ulse
          title: My Unix & Linux Stack Exchange profile
        - icon: github-alt
          url: *github
          title: My GitHub profile

source: source
plugins: plugins
destination: deploy
layouts: ../layouts
