exclude:
    - .git
    - CNAME
    - LICENSE

url: http://chrisdown.name
description: Minimalist programmer, designer, and Unix/Linux advocate.

personal:
    name: Chris Down
    job: Sysadmin
    employers:
        - name: IofC
          url: http://iofc.org
        - name: Binary.com
          url: https://binary.com
    email: chris@chrisdown.name
    phones:
        - visual: +60(0)1118625221
          literal: +601118625221
        - visual: +44(0)7926811688
          literal: +447926811688

header:
    links:
        - name: LinkedIn
          url: http://www.linkedin.com/in/chrisldown
        - name: GitHub
          url: https://github.com/cdown
