personal:
    name: &name Chris Down
    job: Sysadmin
    employers: {
        "Initiatives of Change":"http://iofc.org",
        "BetOnMarkets":"https://betonmarkets.com",
    }
    email: chris@chrisdown.name

name: *name
url: "http://chrisdown.name"

header:
    links: {
        git: "http://git.chrisdown.name/cgit/",
    }

footer:
    links: {
        GitHub: "https://github.com/cdown/",
        "Stack Exchange": "http://stackexchange.com/users/912213/chris-down?tab=accounts"
    }
