auto: true

name: &name Chris Down
url: "http://chrisdown.name"

links:
    iofc: &iofc-url "http://iofc.org"
    bom: &bom-url "https://betonmarkets.com"
    github: &github-url "https://github.com/cdown"
    stackexchange: &stackexchange-url "http://stackexchange.com/users/912213/chris-down?tab=accounts"
    aur: &aur-url "https://aur.archlinux.org/packages/?SeB=m&amp;K=cdown"

personal:
    name: *name
    job: Sysadmin
    employers:
        - name: "Initiatives of Change"
          url: *iofc-url
        - name: "BetOnMarkets"
          url: *bom-url
    email:
        scrim: chrisdown
        account: chris

header:
    links:
        - name: projects
          url: /projects

footer:
    links:
        - name: GitHub
          url: *github-url
        - name: Stack Exchange
          url: *stackexchange-url

projects:
    - name: clarity
      path: "/illcode/clarity"
      description: Digital signage for minimalists
    - name: mac-cel
      path: "/cdown/mac-cel"
      description: Disable mouse/trackpad acceleration on Mac OSX
    - name: pyaur
      path: "/cdown/pyaur"
      description: Python 3 (and 2) Arch User Repository interface
    - name: wifilogin
      path: "/cdown/wifilogin"
      description: Bypass captive portal login
    - name: yturl
      path: "/cdown/yturl"
      description: Gets direct URLs to YouTube media
